# Generated by Django 6.0.5 on 2026-05-27 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contaagendada',
            name='recorrente',
            field=models.BooleanField(default=False),
        ),
    ]
